import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'leaflet/dist/leaflet.css';
import { Providers } from './providers';
import "@/lib/i18n";
import ClientLayout from "./components/Template/ClientLayout";
import { ReduxProvider } from '@/redux/provider'
import { Toaster } from "react-hot-toast";
import Loading from "./components/Loading/Loading";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi" className='dark' suppressHydrationWarning={true}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ReduxProvider>
          <Providers>
            <Loading />
            <Toaster position="top-center" />
            <ClientLayout>{children}</ClientLayout>
          </Providers>
        </ReduxProvider>
      </body>
    </html>
  );
}
